require: rubocop-performance
AllCops:
  TargetRubyVersion: 2.6
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Metrics/LineLength:
  Max: 150
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false